# Generated by Django 2.2.16 on 2021-08-26 19:28

import apps.shop.utils
from django.db import migrations, models
import django.db.models.deletion
import django_2gis_maps.fields
import django_2gis_maps.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='О Ganador')),
                ('title_production', models.CharField(max_length=120, verbose_name='Продукция Ganador')),
                ('text_production', models.TextField(blank=True, verbose_name='Описание')),
                ('title_manufacture', models.CharField(max_length=120, verbose_name='Одежда под ключ')),
                ('text_manufacture', models.TextField(blank=True, verbose_name='Описание')),
                ('fabric_image', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение фабрики')),
                ('image_1', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение 1')),
                ('image_2', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение 2')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('in_slider', models.BooleanField(verbose_name='В слайдере главной страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_2gis_maps.fields.AddressField(max_length=200, verbose_name='Адрес')),
                ('geolocation', django_2gis_maps.fields.GeoLocationField(verbose_name='Геолокация')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('mail', models.EmailField(blank=True, max_length=60, verbose_name='Электронная почта')),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='Инстаграм')),
                ('vk', models.CharField(blank=True, max_length=30, verbose_name='ВКонтакте')),
                ('phone_1', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 2')),
                ('work_time', models.CharField(blank=True, max_length=60, verbose_name='Рабочее время')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
            bases=(django_2gis_maps.mixins.DoubleGisMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Сcылка')),
                ('image', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер главной страницы',
                'verbose_name_plural': 'Баннер главной страницы',
            },
        ),
        migrations.CreateModel(
            name='MainPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Сcылка')),
                ('image', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение главной страницы',
                'verbose_name_plural': 'Изображения главной страницы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.CharField(max_length=120, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('is_active', models.BooleanField(verbose_name='Отобразить на странице')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='shop.Collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.shop.utils.image_upload_to, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['image'],
            },
        ),
        migrations.CreateModel(
            name='ProductAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительные характеристики товара',
                'verbose_name_plural': 'Дополнительные характеристики товара',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='size_products', to='shop.Size', verbose_name='Размер'),
        ),
    ]
