# Generated by Django 2.2.16 on 2021-08-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='in_clothes',
            field=models.BooleanField(default=True, verbose_name='Одежда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='in_about_us',
            field=models.BooleanField(verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='in_main',
            field=models.BooleanField(verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Сcылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название ccылки'),
        ),
    ]
