# Generated by Django 2.2.16 on 2021-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['id'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='mainpageimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение главной страницы', 'verbose_name_plural': 'Изображения главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productadditional',
            options={'ordering': ['id'], 'verbose_name': 'Дополнительные характеристики товара', 'verbose_name_plural': 'Дополнительные характеристики товара'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['id'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='url_1',
            field=models.URLField(default=None, verbose_name='Сcылка 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='url_2',
            field=models.URLField(default=None, verbose_name='Сcылка 2'),
            preserve_default=False,
        ),
    ]
