# Generated by Django 2.2.16 on 2021-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210824_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='material',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='season',
        ),
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок'),
        ),
    ]
