# Generated by Django 2.2.16 on 2021-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210827_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['my_order'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='mainpageimage',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение главной страницы', 'verbose_name_plural': 'Изображения главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productadditional',
            options={'ordering': ['my_order'], 'verbose_name': 'Дополнительные характеристики товара', 'verbose_name_plural': 'Дополнительные характеристики товара'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['my_order'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='collection',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainpageimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productadditional',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
